name: second_github_action
on: [push]
jobs: 
  aws_cp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAQQALVHVS4TOEEE4H
          aws-secret-access-key: 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
          aws-region: us-east-1
      - name: upload to S3
        run: aws s3 cp. /'myinstanceppk.ppk' s3://githubactionesagbucket
        
      
